workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - logan.mohseni@singlemindconsulting.com
  ios-sonarcloud:
    name: iOS sonarcloud
    instance_type: mac_pro
    environment:
      vars:
        XCODE_PROJECT: "swiftqube.xcodeproj"
        XCODE_SCHEME: "swiftqube"
        BUNDLE_ID: "io.codemagic.swiftqube"
        SONAR_TOKEN: Encrypted(YjI2OTM3NDY0YWFiN2ZkOWNhZTU2ZWM2OWUzZjYzMTBmMWRlNTdmNQ==)
        SONAR_PROJECT_KEY: Encrypted(bG1vaHNlbmktc21jX0ZsdXR0ZXItc29uYXJxdWJl)
        SONAR_ORG_KEY: Encrypted(bG1vaHNlbmktc21j)
      xcode: 12.5
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Sonar Scanner
        script: | 
          brew install sonar-scanner
      - name: Generate debug build
        script: | 
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' \
          -derivedDataPath Build/ \
          -enableCodeCoverage YES \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Convert coverage report to Sonarqube format
        script: |             
          bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
      - name: Generate and upload code analysis report
        script: |  
          export PATH=$PATH:$FCI_BUILD_DIR/sonar-scanner/bin
          
          sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.organization=$SONAR_ORG_KEY \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.projectVersion=1.0.0 \
          -Dsonar.sources=. \
          -Dsonar.cfamily.build-wrapper-output.bypass=true \
          -Dsonar.coverageReportPaths=sonarqube-generic-coverage.xml \
          -Dsonar.c.file.suffixes=- \
          -Dsonar.cpp.file.suffixes=- \
          -Dsonar.objc.file.suffixes=- \
          -Dsonar.branch.name=$FCI_BRANCH \
          -Dsonar.branch.target=$FCI_PULL_REQUEST_DEST

